version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: board
      MYSQL_USER: board
      MYSQL_PASSWORD: qwer1513
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql  # 호스트의 db_data 볼륨을 컨테이너의 데이터 디렉토리에 연결
    networks:
      - sbb_1_app-network

  app:
    image: my-tomcat-image
    container_name: my-tomcat-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/board
      SPRING_DATASOURCE_USERNAME: board
      SPRING_DATASOURCE_PASSWORD: qwer1513
    ports:
      - "8082:8080"
    networks:
      - sbb_1_app-network

networks:
  sbb_1_app-network:
    driver: bridge

volumes:
  db_data:  # 명명된 볼륨 정의
